name = "916slabs"
pages_build_output_dir = "./public"  # Directory for static files (e.g., HTML, CSS, JS)

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "916-slabs"
preview_bucket_name = "r2-explorer-bucket"
