name = "916slabs"

main = "src/index.ts"

compatibility_date = "2026-05-23"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

minify = true
send_metrics = true
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"
APP_NAME = "916slabs"

[[kv_namespaces]]
binding = "KV_SLABS"
id = "__916slabs1-workers_sites_assets"

[[r2_buckets]]
binding = "R2_SLABS"
bucket_name = "916-slabs-bucket"

[[services]]
binding = "AG_BELL_SLABS"
service = "916-slabs"

[ai]
binding = "AI_SLABS"

[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"

[placement]
mode = "smart"

[limits]
cpu_ms = 300000
